module.exports = {
    CLEANUP_TICK: 50,
    TASK_TICK: 10,
    METRIC_TICK: 10,
    SURVEY_TICK: 3600,
    MOV_N: 0.2,
    DMG_THRESHOLD: 0.9,
    PART_MULT: 2,
    DEFENSE_PER: 0.01,
    UPGRADE_PER: 0.8,
    MAX_SEARCH_ROOMS: 5,
    SCOUT_TICK: 3600,
}