module.exports = {
    CLEANUP_TICK: 50,
    METRICS_TICK: 10,
    TASK_TICK: 10,
    MOV_N: 0.2,
    DMG_THRESHOLD: 0.9,
    DEFENSE_PER: 0.01,
    UPGRADE_PER: 0.8,
    MAX_ROOM_SEARCH: 3,
    SCOUT_TICK: 86400,
    SCOUT_COOLDOWN: 3600,
    SCOUT_SPAWN: "Spawn1",
    CLEANUP_METRICS_TICK: 120
}